import React, { useEffect, useState } from "react";
import CardCrianca from "./CardCrianca";
import Contato from "./Contato";
import Link from "next/link";
import { IconButton, Button } from "@mui/material";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import Head from "next/head";

const Apadrinhamento = () => {
  const [criancas, setCriancas] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Função que busca dados da API
  useEffect(() => {
    const fetchCriancas = async () => {
      try {
        setLoading(true);
        const response = await fetch("http://localhost:4000/api/criancas");
        console.log(response);
        if (!response.ok) {
          throw new Error("Erro ao buscar dados da API");
        }
        const data = await response.json();

        const formattedData = data.map((item) => ({
          name: item.nome,
          school: item.escola,
          wish: item.cartinha,
          image: item.imagem,
        }));
        setCriancas(formattedData);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchCriancas();
  }, []);

  const styles = {
    pageContainer: {
      textAlign: "center",
      padding: "20px 0px",
      backgroundColor: "#f5f5dc",
      color: "#000000",
      alignSelf: "stretch",
      fontFamily: "Poppins",
    },
    header: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      gap: "520px",
      fontFamily: "Pacifico",
      alignItems: "center",
    },
    title: {
      display: "block",
      fontWeight: "normal",
    },
    cardsContainer: {
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: "24px",
      minWidth: "1000px",
      margin: "0vh 40vh",
    },
    viewAllButton: {
      backgroundColor: "#388e3c",
      border: "none",
      padding: "12px 24px",
      borderRadius: "5px",
      color: "white",
      marginTop: "20px",
      cursor: "pointer",
    },
    loading: {
      margin: "250px",
    },
    error: {
      color: "red",
      marginTop: "20px",
    },
  };

  return (
    <>
      <Head>
        <title>Apadrinhar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/tabIcon.png" />
      </Head>
      <div>
        <div style={styles.pageContainer}>
          <div style={styles.header}>
            <h1 style={styles.title}>Realize o sonho de uma criança</h1>
            <Link href="/" passHref>
              <IconButton aria-label="voltar">
                <ArrowBackIcon />
              </IconButton>
            </Link>
          </div>
          {loading ? (
            <div style={styles.loading}>
              <p>Carregando dados...</p>
            </div>
          ) : error ? (
            <div style={styles.error}>
              <p>{error}</p>
            </div>
          ) : (
            <div style={styles.cardsContainer}>
              {criancas.map((crianca, index) => (
                <CardCrianca
                  key={index}
                  name={crianca.name}
                  school={crianca.school}
                  wish={crianca.wish}
                  image={crianca.image}
                />
              ))}
            </div>
          )}
          <Button style={styles.viewAllButton}>Ver todos os desejos</Button>
        </div>
        <Contato />
      </div>
    </>
  );
};

export default Apadrinhamento;
