import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Button, StyledInput, HelperText, FormControl, Label } from "@mui/material";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div> 
              {/* O HTML vai dentro desta <div></div> */}
        <nav style={{background: 'RGBA(255,255,255,0.2)', display:'flex', AlignItems: 'center'}}>
          <h3>Papai Noel</h3>
          <Button style={{color:'white', }} variant="text">Sobre</Button>
          <Button style={{color:'white'}} variant="text">Faça um pedido</Button>
          <Button style={{color:'white'}} variant="text">Apadrinhe</Button>
          <Button style={{color:'white'}} variant="text">Cadastra-se</Button>
          <Button style={{backgroundColor: 'green', color:'white'}} variant="text">Login</Button>
        </nav>
      </div>
    </>
  );
}

export function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div> 
              {/* O HTML vai dentro desta <div></div> */}
        <h1>Este espaço é para fazer o login</h1>
        
      </div>
    </>
  );
}

export function Sobre() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div> 
              {/* O HTML vai dentro desta <div></div> */}
        <h1>Este espaço é para fazer o login</h1>
        <h3>Sobre o Projeto</h3>
        <p>
        O Projeto Noel nasceu do desejo de proporcionar um Natal mais feliz para crianças em situação de vulnerabilidade. Nossa missão é conectar escolas e padrinhos dispostos a realizar os sonhos das crianças por meio da doação de presentes.
      </p>
      <p>
        Junte-se a nós nesta causa e faça a diferença na vida de uma criança neste Natal!
      </p>
      </div>
    </>
  );
}

export function Apadrinhar() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div> 
              {/* O HTML vai dentro desta <div></div> */}
        <h1>Este espaço é para fazer o login</h1>
        
        <Home/>
        
      </div>
    </>
  );
}

export function Formulario() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div> 
              {/* O HTML vai dentro desta <div></div> */}
        <h1>Faça um pedido.</h1>

        <form action="processa_upload.php" method="post" encType="multipart/form-data">
          
          <fieldset class="grupo">
            <div class="campo">
              <label for="crianca">Nome da criança</label>
              <input type="crianca" id="name" name="name" placeholder=" Digite o nome da criança..."/>
            </div>
            <div class="campo">
              <label for="turma">Turma</label>
              <input type="turma" id="name" name="name" placeholder="Digite a turma..."/>
            </div>
            <div class="campo">
              <label for="escola">INEP da escola</label>
              <input type="escola" id="name" name="name" placeholder="Digite a inep da escola..."/>
            </div>
            <div class="campo">
              <label for="desejoDeNatal">O que você gostaria de ganhar no natal ?</label>
              <input type="desejoDeNatal" id="name" name="name" placeholder="O que você quer ganhar de natal ?"/>
            </div>
            <div class="campo">
              <label for="file">Faça um upload da cartinha<i class="fas fa-cloud-upload-alt"></i></label>
              <input 
                type="file" name="input_file" placeholder="Select a file..."/>
            </div>
            <button class="button" align="reight">Voltar</button>
          </fieldset>
        </form>
        
        <Home/>
        
      </div>
    </>
  );
}